name: Blank Issue
description: Create a blank issue
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or query.
    validations:
      required: true
