name: Documentation Issue
description: Improvements or corrections for provider documentation
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be updated in the documentation?
    validations:
      required: true
