// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/vmware/terraform-provider-sspi/internal/client/iam_client"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &RoleBindingResource{}
	_ resource.ResourceWithConfigure   = &RoleBindingResource{}
	_ resource.ResourceWithImportState = &RoleBindingResource{}
)

// NewRoleBindingResource is a helper function to simplify the provider implementation.
func NewRoleBindingResource() resource.Resource {
	return &RoleBindingResource{}
}

// RoleBindingResource is the resource implementation.
type RoleBindingResource struct {
	client *iam_client.ClientWithResponses
}

// RoleBindingResourceModel describes the resource data model.
type RoleBindingResourceModel struct {
	ID         types.String `tfsdk:"id"`
	EntityName types.String `tfsdk:"entity_name"`
	UserType   types.String `tfsdk:"user_type"`
	Roles      types.List   `tfsdk:"roles"`
}

func (r *RoleBindingResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_role_binding"
}

func (r *RoleBindingResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Grants one or more roles to a remote (LDAP) user or remote (LDAP) group on the " +
			"SSPI appliance.\n\n" +
			"**Local users cannot be granted roles through this API** — `POST /sspi/iam/role-bindings` only " +
			"accepts `REMOTE_USER`/`REMOTE_GROUP` entities; use `sspi_user_password` for local account " +
			"password management instead.\n\n" +
			"`Update` performs a full replacement of `roles` (not a merge) — any role currently held but " +
			"omitted from the config is revoked.\n\n" +
			"Corresponds to `POST/GET/PUT/DELETE /sspi/iam/role-bindings[/{binding-id}]`.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the role binding, generated by the API.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"entity_name": schema.StringAttribute{
				MarkdownDescription: "The user or group being granted roles. For LDAP users and groups this is " +
					"typically the principal name returned by `GET /sspi/iam/ldap-identity-sources/search`.",
				Required: true,
			},
			"user_type": schema.StringAttribute{
				MarkdownDescription: "Whether `entity_name` identifies a remote LDAP user or a remote LDAP group. " +
					"Must be `REMOTE_USER` or `REMOTE_GROUP` — `LOCAL_USER` is rejected by the API for this resource.",
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf("REMOTE_USER", "REMOTE_GROUP"),
				},
			},
			"roles": schema.ListAttribute{
				MarkdownDescription: "Roles to grant to `entity_name` (e.g. `ENTERPRISE_ADMIN`, `AUDITOR`, " +
					"`SUPPORT_BUNDLE_COLLECTOR`). On `Update`, this list fully replaces the entity's existing roles.",
				Required:    true,
				ElementType: types.StringType,
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
					listvalidator.ValueStringsAre(
						stringvalidator.OneOf(string(iam_client.AUDITOR), string(iam_client.ENTERPRISEADMIN), string(iam_client.SUPPORTBUNDLECOLLECTOR)),
					),
				},
			},
		},
	}
}

func (r *RoleBindingResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	clientProvider, ok := req.ProviderData.(interface {
		GetIAM() *iam_client.ClientWithResponses
	})

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected provider data with GetIAM(), got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = clientProvider.GetIAM()
	if r.client == nil {
		resp.Diagnostics.AddError(
			"SSPI Appliance Not Configured",
			"This resource requires the SSPI appliance connection to be configured on the provider "+
				"(\"sspi_host\", \"sspi_username\", and \"sspi_password\", or the SSPI_HOST, SSPI_USERNAME, "+
				"and SSPI_PASSWORD environment variables).",
		)
		return
	}
}

// rolesFromList converts the Terraform roles list into the generated []iam_client.Role slice.
func rolesFromList(ctx context.Context, l types.List) []iam_client.Role {
	var roleNames []string
	l.ElementsAs(ctx, &roleNames, false) //nolint:errcheck // best-effort; Terraform validates the list is all strings before this runs
	roles := make([]iam_client.Role, 0, len(roleNames))
	for _, name := range roleNames {
		roles = append(roles, iam_client.Role{Role: iam_client.SspInstallerRole(name)})
	}
	return roles
}

// rolesToList converts the API's []Role slice into a Terraform roles list.
func rolesToList(roles []iam_client.Role) types.List {
	values := make([]types.String, 0, len(roles))
	for _, ro := range roles {
		values = append(values, types.StringValue(string(ro.Role)))
	}
	listVal, _ := types.ListValueFrom(context.Background(), types.StringType, values) //nolint:errcheck // values are always plain strings, cannot fail
	return listVal
}

func (r *RoleBindingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data RoleBindingResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Creating SSPI Role Binding")

	body := iam_client.RoleBinding{
		EntityName: data.EntityName.ValueString(),
		UserType:   Ptr(iam_client.UserType(data.UserType.ValueString())),
		Roles:      rolesFromList(ctx, data.Roles),
	}

	createResp, err := r.client.BindRolesToEntityWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating SSPI Role Binding", "Could not create role binding: "+err.Error())
		return
	}

	if createResp.StatusCode() != http.StatusOK || createResp.JSON200 == nil {
		resp.Diagnostics.AddError(
			"Error creating SSPI Role Binding",
			fmt.Sprintf("Unexpected API response: %d: %s", createResp.StatusCode(), string(createResp.Body)),
		)
		return
	}

	mapRoleBindingToState(createResp.JSON200, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RoleBindingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data RoleBindingResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Reading SSPI Role Binding", map[string]interface{}{"id": data.ID.ValueString()})

	readResp, err := r.client.GetRoleBindingWithResponse(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading SSPI Role Binding", "Could not read role binding: "+err.Error())
		return
	}

	if readResp.StatusCode() == http.StatusNotFound {
		resp.State.RemoveResource(ctx)
		return
	}

	if readResp.JSON200 == nil {
		resp.Diagnostics.AddError(
			"Error reading SSPI Role Binding",
			fmt.Sprintf("Unexpected response from API: %d: %s", readResp.StatusCode(), string(readResp.Body)),
		)
		return
	}

	mapRoleBindingToState(readResp.JSON200, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RoleBindingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data RoleBindingResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Updating SSPI Role Binding", map[string]interface{}{"id": data.ID.ValueString()})

	// Full replacement per the API's own documentation: fetch the current
	// _revision first so this PUT isn't rejected by optimistic locking.
	current, err := r.client.GetRoleBindingWithResponse(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading current SSPI Role Binding", "Could not read role binding: "+err.Error())
		return
	}
	if current.JSON200 == nil {
		resp.Diagnostics.AddError(
			"Error reading current SSPI Role Binding",
			fmt.Sprintf("Unexpected response from API: %d: %s", current.StatusCode(), string(current.Body)),
		)
		return
	}

	body := iam_client.RoleBinding{
		EntityName:         data.EntityName.ValueString(),
		UserType:           Ptr(iam_client.UserType(data.UserType.ValueString())),
		Roles:              rolesFromList(ctx, data.Roles),
		UnderscoreRevision: current.JSON200.UnderscoreRevision,
	}

	updateResp, err := r.client.UpdateRolesToEntityWithResponse(ctx, data.ID.ValueString(), body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating SSPI Role Binding", "Could not update role binding: "+err.Error())
		return
	}

	if updateResp.StatusCode() != http.StatusOK || updateResp.JSON200 == nil {
		resp.Diagnostics.AddError(
			"Error updating SSPI Role Binding",
			fmt.Sprintf("Unexpected API response: %d: %s", updateResp.StatusCode(), string(updateResp.Body)),
		)
		return
	}

	mapRoleBindingToState(updateResp.JSON200, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RoleBindingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data RoleBindingResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Deleting SSPI Role Binding", map[string]interface{}{"id": data.ID.ValueString()})

	deleteResp, err := r.client.DeleteRolesToEntityWithResponse(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error deleting SSPI Role Binding", "Could not delete role binding: "+err.Error())
		return
	}

	if deleteResp.StatusCode() != http.StatusOK && deleteResp.StatusCode() != http.StatusNoContent && deleteResp.StatusCode() != http.StatusNotFound {
		resp.Diagnostics.AddError(
			"Error deleting SSPI Role Binding",
			fmt.Sprintf("Unexpected response from API: %d: %s", deleteResp.StatusCode(), string(deleteResp.Body)),
		)
	}
}

func (r *RoleBindingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func mapRoleBindingToState(rb *iam_client.RoleBinding, data *RoleBindingResourceModel) {
	if rb.Id != nil {
		data.ID = types.StringValue(*rb.Id)
	}
	data.EntityName = types.StringValue(rb.EntityName)
	if rb.UserType != nil {
		data.UserType = types.StringValue(string(*rb.UserType))
	}
	data.Roles = rolesToList(rb.Roles)
}

// Ptr returns a pointer to the given value.
func Ptr[T any](v T) *T {
	return &v
}
