// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

// Package depot_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package depot_client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BundleStatus.
const (
	ATTACHED   BundleStatus = "ATTACHED"
	CANCELLED  BundleStatus = "CANCELLED"
	ERROR      BundleStatus = "ERROR"
	FAILED     BundleStatus = "FAILED"
	INPROGRESS BundleStatus = "IN_PROGRESS"
	INUSE      BundleStatus = "IN_USE"
	READY      BundleStatus = "READY"
)

// Valid indicates whether the value is a known member of the BundleStatus enum.
func (e BundleStatus) Valid() bool {
	switch e {
	case ATTACHED:
		return true
	case CANCELLED:
		return true
	case ERROR:
		return true
	case FAILED:
		return true
	case INPROGRESS:
		return true
	case INUSE:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// Defines values for BundleType.
const (
	AVIOPERATIONS      BundleType = "AVI_OPERATIONS"
	AVIOPERATIONSPATCH BundleType = "AVI_OPERATIONS_PATCH"
	BMS                BundleType = "BMS"
	INSTALLER          BundleType = "INSTALLER"
	PLATFORM           BundleType = "PLATFORM"
	PLATFORMPATCH      BundleType = "PLATFORM_PATCH"
	SVM                BundleType = "SVM"
)

// Valid indicates whether the value is a known member of the BundleType enum.
func (e BundleType) Valid() bool {
	switch e {
	case AVIOPERATIONS:
		return true
	case AVIOPERATIONSPATCH:
		return true
	case BMS:
		return true
	case INSTALLER:
		return true
	case PLATFORM:
		return true
	case PLATFORMPATCH:
		return true
	case SVM:
		return true
	default:
		return false
	}
}

// AddonBundle Information about an add-on bundle.
type AddonBundle struct {
	// BundleType Type of a bundle, identifying its purpose and content type.
	BundleType *BundleType `json:"bundle_type,omitempty"`

	// BundleVersion Version string for this add-on component. May differ from the parent bundle
	// version for independently versioned components.
	BundleVersion *string `json:"bundle_version,omitempty"`

	// Description Description explaining what this add-on provides.
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for this add-on bundle. This ID can be used to reference
	// the add-on in deployment configurations.
	Id *string `json:"id,omitempty"`

	// Required If true, this add-on must be included during deployment for the parent bundle
	// to function correctly. Optional add-ons can be excluded if not needed.
	Required *bool `json:"required,omitempty"`
}

// AsyncApiResponse API response for asynchronous operations.
//
// Example: {"id":"b8f47985-22ed-3193-bca8-11c7b025cbce","status_url":"/operation/status"}
type AsyncApiResponse struct {
	// Id UUID identifier of the response.
	Id *string `json:"id,omitempty"`

	// StatusUrl The URL to check the status of the operation.
	StatusUrl *string `json:"status_url,omitempty"`
}

// Bundle Information about a bundle.
type Bundle struct {
	// UnderscoreCreateTime Timestamp in milliseconds since epoch.
	UnderscoreCreateTime *EpochMsTimestamp `json:"_create_time,omitempty"`

	// UnderscoreCreateUser ID of the user who created this resource.
	UnderscoreCreateUser *string `json:"_create_user,omitempty"`

	// UnderscoreLastModifiedTime Timestamp in milliseconds since epoch.
	UnderscoreLastModifiedTime *EpochMsTimestamp `json:"_last_modified_time,omitempty"`

	// UnderscoreLastModifiedUser ID of the user who last modified this resource.
	UnderscoreLastModifiedUser *string `json:"_last_modified_user,omitempty"`

	// UnderscoreResourceType The type of this resource.
	UnderscoreResourceType *string `json:"_resource_type,omitempty"`

	// UnderscoreRevision The _revision property describes the current revision of the resource.
	// To prevent clients from overwriting each other's changes, update operations must include the current _revision of the resource in request body, which clients should obtain by issuing a GET operation.
	// 1. First, issue a GET request to current state of the resource. 2. Change the payload as needed to PUT. Retain the _revision as returned in the GET call. 3. Include this _revision value in the PUT request body.
	// If the `_revision` field is missing, the request will be rejected with HTTP 428 (Precondition Required). If the `_revision` is stale (another update occurred), the request will be rejected with HTTP 412 (Precondition Failed).
	UnderscoreRevision *int `json:"_revision,omitempty"`

	// UnderscoreSystemOwned Indicates system owned resource.
	UnderscoreSystemOwned *bool `json:"_system_owned,omitempty"`

	// Addons List of add-on bundles included in this bundle. These add-on bundles are
	// attached by default when the parent bundle is deployed.
	Addons []AddonBundle `json:"addons"`

	// BundleType Type of a bundle, identifying its purpose and content type.
	BundleType *BundleType `json:"bundle_type,omitempty"`

	// BundleVersion Version string identifying the build and release of this bundle.
	BundleVersion *string `json:"bundle_version,omitempty"`

	// Description Description of this resource.
	Description *string `json:"description,omitempty"`

	// DisplayName Name for the resource to be displayed in logs or GUI. Defaults to ID if not set.
	DisplayName *string `json:"display_name,omitempty"`

	// Id Unique identifier of this resource.
	Id *string `json:"id,omitempty"`

	// Message Human-readable message providing additional context about the current status.
	// Contains error details when status is ERROR or FAILED, or progress updates
	// during processing.
	Message *string `json:"message,omitempty"`

	// PackagedTime Timestamp in milliseconds since epoch.
	PackagedTime EpochMsTimestamp `json:"packaged_time"`

	// ParentId For patch bundles (PLATFORM_PATCH, etc.), this references the ID
	// of the base bundle that must be available first. Null for non-patch bundles.
	ParentId *string `json:"parent_id,omitempty"`

	// Progress Upload/processing progress as a percentage (0-100). Only meaningful when status
	// is IN_PROGRESS. Remains at 100 for completed operations.
	Progress *int `json:"progress,omitempty"`

	// SiteIds Identifiers of the local managers or sites this resource corresponds to.
	SiteIds *[]string `json:"site_ids,omitempty"`

	// Size Total size of the bundle file in bytes.
	Size *int `json:"size,omitempty"`

	// Status Current state of the bundle:
	// * IN_PROGRESS: Upload/download in progress, check progress field for percentage
	// * READY: Available for deployment and use
	// * IN_USE: Bundle is actively used and cannot be deleted
	// * ATTACHED: Bundle is attached to a platform instance
	// * CANCELLED: Upload was cancelled by user or system
	// * ERROR: Processing failed due to unexpected internal system errors
	// * FAILED: Processing failed due to validation errors
	Status *BundleStatus `json:"status,omitempty"`
}

// BundleStatus Current state of the bundle:
// * IN_PROGRESS: Upload/download in progress, check progress field for percentage
// * READY: Available for deployment and use
// * IN_USE: Bundle is actively used and cannot be deleted
// * ATTACHED: Bundle is attached to a platform instance
// * CANCELLED: Upload was cancelled by user or system
// * ERROR: Processing failed due to unexpected internal system errors
// * FAILED: Processing failed due to validation errors
type BundleStatus string

// BundleType Type of a bundle, identifying its purpose and content type.
type BundleType string

// EpochMsTimestamp Timestamp in milliseconds since epoch.
type EpochMsTimestamp = int64

// Error Error
type Error struct {
	// ErrorCode HTTP Status or Application error code.
	ErrorCode int `json:"error_code"`

	// ErrorMessage Message describing the error.
	ErrorMessage string `json:"error_message"`

	// ModuleName Module where the error happened.
	ModuleName *string `json:"module_name,omitempty"`
}

// ListBundles Paginated list of bundles with metadata for navigation. Use the pagination fields
// to iterate through large result sets.
type ListBundles struct {
	// NumberOfResults This is the number of results returned in the current page.
	NumberOfResults *int64 `json:"number_of_results,omitempty"`

	// Offset Offset pagination parameter used to exclude from a response the first N items of a resource collection.
	// This reflects the offset provided in the request.
	Offset *int `json:"offset,omitempty"`

	// Results Array of bundle objects matching the query criteria. Each bundle includes its
	// current status and metadata.
	Results *[]Bundle `json:"results,omitempty"`

	// SortAscending If true, results are sorted in ascending order.
	SortAscending *bool `json:"sort_ascending,omitempty"`

	// SortBy Field by which records are sorted.
	SortBy *string `json:"sort_by,omitempty"`

	// TotalPages Total pages present, based on page_size.
	TotalPages *int64 `json:"total_pages,omitempty"`

	// TotalResultCount Total number of results across all pages.
	TotalResultCount *int64 `json:"total_result_count,omitempty"`
}

// ListResult Base class for list results from collections.
type ListResult struct {
	// NumberOfResults This is the number of results returned in the current page.
	NumberOfResults *int64 `json:"number_of_results,omitempty"`

	// Offset Offset pagination parameter used to exclude from a response the first N items of a resource collection.
	// This reflects the offset provided in the request.
	Offset *int `json:"offset,omitempty"`

	// SortAscending If true, results are sorted in ascending order.
	SortAscending *bool `json:"sort_ascending,omitempty"`

	// SortBy Field by which records are sorted.
	SortBy *string `json:"sort_by,omitempty"`

	// TotalPages Total pages present, based on page_size.
	TotalPages *int64 `json:"total_pages,omitempty"`

	// TotalResultCount Total number of results across all pages.
	TotalResultCount *int64 `json:"total_result_count,omitempty"`
}

// LocalUpload Configuration for uploading a bundle file directly via multipart form data.
type LocalUpload struct {
	// File Binary content of the bundle file
	File openapi_types.File `json:"file"`
}

// ManagedResource Base type for resources that are managed by API clients.
type ManagedResource struct {
	// UnderscoreCreateTime Timestamp in milliseconds since epoch.
	UnderscoreCreateTime *EpochMsTimestamp `json:"_create_time,omitempty"`

	// UnderscoreCreateUser ID of the user who created this resource.
	UnderscoreCreateUser *string `json:"_create_user,omitempty"`

	// UnderscoreLastModifiedTime Timestamp in milliseconds since epoch.
	UnderscoreLastModifiedTime *EpochMsTimestamp `json:"_last_modified_time,omitempty"`

	// UnderscoreLastModifiedUser ID of the user who last modified this resource.
	UnderscoreLastModifiedUser *string `json:"_last_modified_user,omitempty"`

	// UnderscoreResourceType The type of this resource.
	UnderscoreResourceType *string `json:"_resource_type,omitempty"`

	// UnderscoreRevision The _revision property describes the current revision of the resource.
	// To prevent clients from overwriting each other's changes, update operations must include the current _revision of the resource in request body, which clients should obtain by issuing a GET operation.
	// 1. First, issue a GET request to current state of the resource. 2. Change the payload as needed to PUT. Retain the _revision as returned in the GET call. 3. Include this _revision value in the PUT request body.
	// If the `_revision` field is missing, the request will be rejected with HTTP 428 (Precondition Required). If the `_revision` is stale (another update occurred), the request will be rejected with HTTP 412 (Precondition Failed).
	UnderscoreRevision *int `json:"_revision,omitempty"`

	// UnderscoreSystemOwned Indicates system owned resource.
	UnderscoreSystemOwned *bool `json:"_system_owned,omitempty"`

	// Description Description of this resource.
	Description *string `json:"description,omitempty"`

	// DisplayName Name for the resource to be displayed in logs or GUI. Defaults to ID if not set.
	DisplayName *string `json:"display_name,omitempty"`

	// Id Unique identifier of this resource.
	Id *string `json:"id,omitempty"`

	// SiteIds Identifiers of the local managers or sites this resource corresponds to.
	SiteIds *[]string `json:"site_ids,omitempty"`
}

// RemoteUpload Configuration for importing a bundle from a remote location.
// The URL must be accessible from the installer.
//
// Example: {"url":"https://example.com/resources/bundle.tar"}
type RemoteUpload struct {
	// Url HTTP(S) URL pointing to a valid bundle file.
	// The URL must be accessible without authentication.
	Url string `json:"url"`
}

// Resource Base class for resources.
type Resource struct {
	// UnderscoreCreateTime Timestamp in milliseconds since epoch.
	UnderscoreCreateTime *EpochMsTimestamp `json:"_create_time,omitempty"`

	// UnderscoreCreateUser ID of the user who created this resource.
	UnderscoreCreateUser *string `json:"_create_user,omitempty"`

	// UnderscoreLastModifiedTime Timestamp in milliseconds since epoch.
	UnderscoreLastModifiedTime *EpochMsTimestamp `json:"_last_modified_time,omitempty"`

	// UnderscoreLastModifiedUser ID of the user who last modified this resource.
	UnderscoreLastModifiedUser *string `json:"_last_modified_user,omitempty"`

	// UnderscoreResourceType The type of this resource.
	UnderscoreResourceType *string `json:"_resource_type,omitempty"`

	// UnderscoreRevision The _revision property describes the current revision of the resource.
	// To prevent clients from overwriting each other's changes, update operations must include the current _revision of the resource in request body, which clients should obtain by issuing a GET operation.
	// 1. First, issue a GET request to current state of the resource. 2. Change the payload as needed to PUT. Retain the _revision as returned in the GET call. 3. Include this _revision value in the PUT request body.
	// If the `_revision` field is missing, the request will be rejected with HTTP 428 (Precondition Required). If the `_revision` is stale (another update occurred), the request will be rejected with HTTP 412 (Precondition Failed).
	UnderscoreRevision *int `json:"_revision,omitempty"`

	// UnderscoreSystemOwned Indicates system owned resource.
	UnderscoreSystemOwned *bool `json:"_system_owned,omitempty"`

	// Description Description of this resource.
	Description *string `json:"description,omitempty"`

	// DisplayName Name for the resource to be displayed in logs or GUI. Defaults to ID if not set.
	DisplayName *string `json:"display_name,omitempty"`

	// Id Unique identifier of this resource.
	Id *string `json:"id,omitempty"`

	// SiteIds Identifiers of the local managers or sites this resource corresponds to.
	SiteIds *[]string `json:"site_ids,omitempty"`
}

// BundleTypeFilter Type of a bundle, identifying its purpose and content type.
type BundleTypeFilter = BundleType

// Offset defines model for Offset.
type Offset = int

// PageSize defines model for PageSize.
type PageSize = int32

// SortAscending defines model for SortAscending.
type SortAscending = bool

// SortBy defines model for SortBy.
type SortBy = string

// BadRequest Error
type BadRequest = Error

// Forbidden Error
type Forbidden = Error

// PreconditionFailed Error
type PreconditionFailed = Error

// PreconditionRequired Error
type PreconditionRequired = Error

// TooManyRequests Error
type TooManyRequests = Error

// Unauthorized Error
type Unauthorized = Error

// GetBundlesParams defines parameters for GetBundles.
type GetBundlesParams struct {
	// Offset Offset pagination parameter used to exclude from a response the first N items of a resource
	// collection. Combine the offset and the page_size options to request a particular set or page
	// of items.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// PageSize Number of records to be returned in the API request from the provided offset
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// SortAscending True, if the list of records returned need to be sorted in ascending order, false otherwise.
	SortAscending *SortAscending `form:"sort_ascending,omitempty" json:"sort_ascending,omitempty"`

	// SortBy The parameter name on which to sort the list of records. Only top-level parameters in the returned list of records will be supported. If not provided, system will define the parameter by which results are sorted.
	SortBy *SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// UploadLocalBundleParams defines parameters for UploadLocalBundle.
type UploadLocalBundleParams struct {
	// Type Filter bundles by type. When specified, only bundles matching this type will be
	// processed.
	Type *BundleTypeFilter `form:"type,omitempty" json:"type,omitempty"`
}

// UploadRemoteBundleParams defines parameters for UploadRemoteBundle.
type UploadRemoteBundleParams struct {
	// Type Filter bundles by type. When specified, only bundles matching this type will be
	// processed.
	Type *BundleTypeFilter `form:"type,omitempty" json:"type,omitempty"`
}

// UploadLocalBundleMultipartRequestBody defines body for UploadLocalBundle for multipart/form-data ContentType.
type UploadLocalBundleMultipartRequestBody = LocalUpload

// UploadRemoteBundleJSONRequestBody defines body for UploadRemoteBundle for application/json ContentType.
type UploadRemoteBundleJSONRequestBody = RemoteUpload

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetBundles List all available bundles
	//
	// Retrieves a paginated list of all bundles available in installer with their current status
	// and metadata.
	//
	// **Usage:**
	// * Use this to discover available bundles before selecting one for deployment
	// * Results are paginated - use the pagination parameters to navigate
	//   large result sets
	//
	// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
	GetBundles(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadLocalBundleWithBody Upload bundle file directly
	//
	// Uploads a bundle file directly to installer via multipart form data.
	// The returned response contains a link to the bundle status endpoint.
	//
	// **Notes:**
	// * File validation and extraction occurs during upload
	// * Invalid bundles will result in FAILED status with diagnostic message
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
	UploadLocalBundleWithBody(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadRemoteBundleWithBody Import bundle from remote URL
	//
	// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
	//
	// **Notes:**
	// * The remote URL must be accessible from the installer.
	// * Bundle validation occurs during download - invalid bundles will result in FAILED status
	//   (broken download, incomplete bundle, bad metadata)
	// * ERROR status is reserved for unexpected internal errors
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundleWithBody(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadRemoteBundle Import bundle from remote URL
	//
	// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
	//
	// **Notes:**
	// * The remote URL must be accessible from the installer.
	// * Bundle validation occurs during download - invalid bundles will result in FAILED status
	//   (broken download, incomplete bundle, bad metadata)
	// * ERROR status is reserved for unexpected internal errors
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundle(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBundle Remove bundle or cancel upload
	//
	// Permanently deletes a bundle or cancels an in-progress upload operation.
	//
	// **Notes:**
	// * If bundle status is IN_PROGRESS, this will cancel the upload and clean up partial data
	// * If bundle status is READY, this will permanently remove the bundle from storage
	// * Once deleted, the bundle cannot be recovered and will need to be uploaded again
	// * Bundles with status IN_USE or ATTACHED cannot be deleted
	//
	// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
	DeleteBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBundle Retrieve bundle details and upload status
	//
	// Fetches the information about a specific bundle including its upload status,
	// version details, and metadata.
	//
	// **Notes:**
	// * Returns `404` if the bundle does not exist or has been deleted
	//
	// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
	GetBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDepotHealth Verify package management service health
	//
	// Performs a lightweight health check on the package management service to verify
	// that it is operational.
	//
	// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
	GetDepotHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetBundles List all available bundles
//
// Retrieves a paginated list of all bundles available in installer with their current status
// and metadata.
//
// **Usage:**
//   - Use this to discover available bundles before selecting one for deployment
//   - Results are paginated - use the pagination parameters to navigate
//     large result sets
//
// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
func (c *Client) GetBundles(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBundlesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadLocalBundleWithBody Upload bundle file directly
//
// Uploads a bundle file directly to installer via multipart form data.
// The returned response contains a link to the bundle status endpoint.
//
// **Notes:**
// * File validation and extraction occurs during upload
// * Invalid bundles will result in FAILED status with diagnostic message
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
func (c *Client) UploadLocalBundleWithBody(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadLocalBundleRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadRemoteBundleWithBody Import bundle from remote URL
//
// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
//
// **Notes:**
//   - The remote URL must be accessible from the installer.
//   - Bundle validation occurs during download - invalid bundles will result in FAILED status
//     (broken download, incomplete bundle, bad metadata)
//   - ERROR status is reserved for unexpected internal errors
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *Client) UploadRemoteBundleWithBody(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadRemoteBundleRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadRemoteBundle Import bundle from remote URL
//
// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
//
// **Notes:**
//   - The remote URL must be accessible from the installer.
//   - Bundle validation occurs during download - invalid bundles will result in FAILED status
//     (broken download, incomplete bundle, bad metadata)
//   - ERROR status is reserved for unexpected internal errors
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *Client) UploadRemoteBundle(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadRemoteBundleRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteBundle Remove bundle or cancel upload
//
// Permanently deletes a bundle or cancels an in-progress upload operation.
//
// **Notes:**
// * If bundle status is IN_PROGRESS, this will cancel the upload and clean up partial data
// * If bundle status is READY, this will permanently remove the bundle from storage
// * Once deleted, the bundle cannot be recovered and will need to be uploaded again
// * Bundles with status IN_USE or ATTACHED cannot be deleted
//
// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
func (c *Client) DeleteBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBundleRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBundle Retrieve bundle details and upload status
//
// Fetches the information about a specific bundle including its upload status,
// version details, and metadata.
//
// **Notes:**
// * Returns `404` if the bundle does not exist or has been deleted
//
// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
func (c *Client) GetBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBundleRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDepotHealth Verify package management service health
//
// Performs a lightweight health check on the package management service to verify
// that it is operational.
//
// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
func (c *Client) GetDepotHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDepotHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBundlesRequest constructs an http.Request for the GetBundles method
func NewGetBundlesRequest(server string, params *GetBundlesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortAscending != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_ascending", *params.SortAscending, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadLocalBundleRequestWithBody constructs an http.Request for the UploadLocalBundle method, with any body, and a specified content type
func NewUploadLocalBundleRequestWithBody(server string, params *UploadLocalBundleParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/local")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadRemoteBundleRequest calls the generic UploadRemoteBundle builder with application/json body
func NewUploadRemoteBundleRequest(server string, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUploadRemoteBundleRequestWithBody(server, params, "application/json", bodyReader)
}

// NewUploadRemoteBundleRequestWithBody constructs an http.Request for the UploadRemoteBundle method, with any body, and a specified content type
func NewUploadRemoteBundleRequestWithBody(server string, params *UploadRemoteBundleParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/remote")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBundleRequest constructs an http.Request for the DeleteBundle method
func NewDeleteBundleRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBundleRequest constructs an http.Request for the GetBundle method
func NewGetBundleRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDepotHealthRequest constructs an http.Request for the GetDepotHealth method
func NewGetDepotHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/depot/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetBundlesWithResponse List all available bundles
	//
	// Retrieves a paginated list of all bundles available in installer with their current status
	// and metadata.
	//
	// **Usage:**
	// * Use this to discover available bundles before selecting one for deployment
	// * Results are paginated - use the pagination parameters to navigate
	//   large result sets
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
	GetBundlesWithResponse(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*GetBundlesResponse, error)

	// UploadLocalBundleWithBodyWithResponse Upload bundle file directly
	//
	// Uploads a bundle file directly to installer via multipart form data.
	// The returned response contains a link to the bundle status endpoint.
	//
	// **Notes:**
	// * File validation and extraction occurs during upload
	// * Invalid bundles will result in FAILED status with diagnostic message
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
	UploadLocalBundleWithBodyWithResponse(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadLocalBundleResponse, error)

	// UploadRemoteBundleWithBodyWithResponse Import bundle from remote URL
	//
	// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
	//
	// **Notes:**
	// * The remote URL must be accessible from the installer.
	// * Bundle validation occurs during download - invalid bundles will result in FAILED status
	//   (broken download, incomplete bundle, bad metadata)
	// * ERROR status is reserved for unexpected internal errors
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundleWithBodyWithResponse(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error)

	// UploadRemoteBundleWithResponse Import bundle from remote URL
	//
	// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
	//
	// **Notes:**
	// * The remote URL must be accessible from the installer.
	// * Bundle validation occurs during download - invalid bundles will result in FAILED status
	//   (broken download, incomplete bundle, bad metadata)
	// * ERROR status is reserved for unexpected internal errors
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundleWithResponse(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error)

	// DeleteBundleWithResponse Remove bundle or cancel upload
	//
	// Permanently deletes a bundle or cancels an in-progress upload operation.
	//
	// **Notes:**
	// * If bundle status is IN_PROGRESS, this will cancel the upload and clean up partial data
	// * If bundle status is READY, this will permanently remove the bundle from storage
	// * Once deleted, the bundle cannot be recovered and will need to be uploaded again
	// * Bundles with status IN_USE or ATTACHED cannot be deleted
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
	DeleteBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteBundleResponse, error)

	// GetBundleWithResponse Retrieve bundle details and upload status
	//
	// Fetches the information about a specific bundle including its upload status,
	// version details, and metadata.
	//
	// **Notes:**
	// * Returns `404` if the bundle does not exist or has been deleted
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
	GetBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetBundleResponse, error)

	// GetDepotHealthWithResponse Verify package management service health
	//
	// Performs a lightweight health check on the package management service to verify
	// that it is operational.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
	GetDepotHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDepotHealthResponse, error)
}

type GetBundlesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListBundles
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *PreconditionFailed
	// JSON428 the response for an HTTP 428 `application/json` response
	JSON428 *PreconditionRequired
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBundlesResponse) GetJSON200() *ListBundles {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetBundlesResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetBundlesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetBundlesResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r GetBundlesResponse) GetJSON412() *PreconditionFailed {
	return r.JSON412
}

// GetJSON428 returns the response for an HTTP 428 `application/json` response
func (r GetBundlesResponse) GetJSON428() *PreconditionRequired {
	return r.JSON428
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r GetBundlesResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetBundlesResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetBundlesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBundlesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBundlesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBundlesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UploadLocalBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *AsyncApiResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *PreconditionFailed
	// JSON428 the response for an HTTP 428 `application/json` response
	JSON428 *PreconditionRequired
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r UploadLocalBundleResponse) GetJSON202() *AsyncApiResponse {
	return r.JSON202
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UploadLocalBundleResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UploadLocalBundleResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UploadLocalBundleResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r UploadLocalBundleResponse) GetJSON412() *PreconditionFailed {
	return r.JSON412
}

// GetJSON428 returns the response for an HTTP 428 `application/json` response
func (r UploadLocalBundleResponse) GetJSON428() *PreconditionRequired {
	return r.JSON428
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r UploadLocalBundleResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UploadLocalBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UploadLocalBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UploadLocalBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadLocalBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadLocalBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UploadRemoteBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *AsyncApiResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *PreconditionFailed
	// JSON428 the response for an HTTP 428 `application/json` response
	JSON428 *PreconditionRequired
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON202() *AsyncApiResponse {
	return r.JSON202
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON412() *PreconditionFailed {
	return r.JSON412
}

// GetJSON428 returns the response for an HTTP 428 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON428() *PreconditionRequired {
	return r.JSON428
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UploadRemoteBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UploadRemoteBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UploadRemoteBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadRemoteBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadRemoteBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *PreconditionFailed
	// JSON428 the response for an HTTP 428 `application/json` response
	JSON428 *PreconditionRequired
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteBundleResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteBundleResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteBundleResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r DeleteBundleResponse) GetJSON412() *PreconditionFailed {
	return r.JSON412
}

// GetJSON428 returns the response for an HTTP 428 `application/json` response
func (r DeleteBundleResponse) GetJSON428() *PreconditionRequired {
	return r.JSON428
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r DeleteBundleResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Bundle
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *PreconditionFailed
	// JSON428 the response for an HTTP 428 `application/json` response
	JSON428 *PreconditionRequired
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBundleResponse) GetJSON200() *Bundle {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetBundleResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetBundleResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetBundleResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r GetBundleResponse) GetJSON412() *PreconditionFailed {
	return r.JSON412
}

// GetJSON428 returns the response for an HTTP 428 `application/json` response
func (r GetBundleResponse) GetJSON428() *PreconditionRequired {
	return r.JSON428
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r GetBundleResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDepotHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *PreconditionFailed
	// JSON428 the response for an HTTP 428 `application/json` response
	JSON428 *PreconditionRequired
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetDepotHealthResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetDepotHealthResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetDepotHealthResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r GetDepotHealthResponse) GetJSON412() *PreconditionFailed {
	return r.JSON412
}

// GetJSON428 returns the response for an HTTP 428 `application/json` response
func (r GetDepotHealthResponse) GetJSON428() *PreconditionRequired {
	return r.JSON428
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r GetDepotHealthResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetDepotHealthResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetDepotHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDepotHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDepotHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDepotHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBundlesWithResponse List all available bundles
//
// Retrieves a paginated list of all bundles available in installer with their current status
// and metadata.
//
// **Usage:**
//   - Use this to discover available bundles before selecting one for deployment
//   - Results are paginated - use the pagination parameters to navigate
//     large result sets
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
func (c *ClientWithResponses) GetBundlesWithResponse(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*GetBundlesResponse, error) {
	rsp, err := c.GetBundles(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBundlesResponse(rsp)
}

// UploadLocalBundleWithBodyWithResponse Upload bundle file directly
//
// Uploads a bundle file directly to installer via multipart form data.
// The returned response contains a link to the bundle status endpoint.
//
// **Notes:**
// * File validation and extraction occurs during upload
// * Invalid bundles will result in FAILED status with diagnostic message
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
func (c *ClientWithResponses) UploadLocalBundleWithBodyWithResponse(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadLocalBundleResponse, error) {
	rsp, err := c.UploadLocalBundleWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadLocalBundleResponse(rsp)
}

// UploadRemoteBundleWithBodyWithResponse Import bundle from remote URL
//
// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
//
// **Notes:**
//   - The remote URL must be accessible from the installer.
//   - Bundle validation occurs during download - invalid bundles will result in FAILED status
//     (broken download, incomplete bundle, bad metadata)
//   - ERROR status is reserved for unexpected internal errors
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *ClientWithResponses) UploadRemoteBundleWithBodyWithResponse(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error) {
	rsp, err := c.UploadRemoteBundleWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadRemoteBundleResponse(rsp)
}

// UploadRemoteBundleWithResponse Import bundle from remote URL
//
// Initiates an asynchronous download and import of a bundle from a remote URL onto installer.
//
// **Notes:**
//   - The remote URL must be accessible from the installer.
//   - Bundle validation occurs during download - invalid bundles will result in FAILED status
//     (broken download, incomplete bundle, bad metadata)
//   - ERROR status is reserved for unexpected internal errors
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *ClientWithResponses) UploadRemoteBundleWithResponse(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error) {
	rsp, err := c.UploadRemoteBundle(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadRemoteBundleResponse(rsp)
}

// DeleteBundleWithResponse Remove bundle or cancel upload
//
// Permanently deletes a bundle or cancels an in-progress upload operation.
//
// **Notes:**
// * If bundle status is IN_PROGRESS, this will cancel the upload and clean up partial data
// * If bundle status is READY, this will permanently remove the bundle from storage
// * Once deleted, the bundle cannot be recovered and will need to be uploaded again
// * Bundles with status IN_USE or ATTACHED cannot be deleted
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
func (c *ClientWithResponses) DeleteBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteBundleResponse, error) {
	rsp, err := c.DeleteBundle(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBundleResponse(rsp)
}

// GetBundleWithResponse Retrieve bundle details and upload status
//
// Fetches the information about a specific bundle including its upload status,
// version details, and metadata.
//
// **Notes:**
// * Returns `404` if the bundle does not exist or has been deleted
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
func (c *ClientWithResponses) GetBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetBundleResponse, error) {
	rsp, err := c.GetBundle(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBundleResponse(rsp)
}

// GetDepotHealthWithResponse Verify package management service health
//
// Performs a lightweight health check on the package management service to verify
// that it is operational.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
func (c *ClientWithResponses) GetDepotHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDepotHealthResponse, error) {
	rsp, err := c.GetDepotHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDepotHealthResponse(rsp)
}

// ParseGetBundlesResponse parses an HTTP response from a GetBundlesWithResponse call
func ParseGetBundlesResponse(rsp *http.Response) (*GetBundlesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBundlesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListBundles
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 428:
		var dest PreconditionRequired
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON428 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUploadLocalBundleResponse parses an HTTP response from a UploadLocalBundleWithResponse call
func ParseUploadLocalBundleResponse(rsp *http.Response) (*UploadLocalBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadLocalBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AsyncApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 428:
		var dest PreconditionRequired
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON428 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUploadRemoteBundleResponse parses an HTTP response from a UploadRemoteBundleWithResponse call
func ParseUploadRemoteBundleResponse(rsp *http.Response) (*UploadRemoteBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadRemoteBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AsyncApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 428:
		var dest PreconditionRequired
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON428 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteBundleResponse parses an HTTP response from a DeleteBundleWithResponse call
func ParseDeleteBundleResponse(rsp *http.Response) (*DeleteBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 428:
		var dest PreconditionRequired
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON428 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetBundleResponse parses an HTTP response from a GetBundleWithResponse call
func ParseGetBundleResponse(rsp *http.Response) (*GetBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Bundle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 428:
		var dest PreconditionRequired
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON428 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetDepotHealthResponse parses an HTTP response from a GetDepotHealthWithResponse call
func ParseGetDepotHealthResponse(rsp *http.Response) (*GetDepotHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDepotHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 428:
		var dest PreconditionRequired
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON428 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
