---
name: dependency-review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: always
