---
name: go-security

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches:
      - main
      - 'branch_*'
      - 'release-*'
    paths-ignore:
      - README.md
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  security:
    name: Go security checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Download Go Modules
        run: go mod download
      - name: Build
        run: go build -v .
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
          repo-checkout: false
